### ISSUE TITLE
Versiyon Talebi

### ISSUE THREAD

**Issue by bilalyilmax** [UnlemBilisim/foribaapi#1]
Merhaba, api için öncelikle teşekkür ederim.
Composer require ile kullanabilmek için versiyon yayınlamanız gerekiyor, bi release oluşturabilir misiniz?
diğer türlü apinizi consol'dan composer'a dahil edemiyorum.

**Comment by bilalyilmax** [comment]
![image](https://user-images.githubusercontent.com/10108441/48967291-34642280-efef-11e8-867f-39e1f9e29b33.png)

**Comment by Orgenus** [comment]
Merhabalar, Güncelleme yapıldı.

composer require unlembilisim/foribaapi:dev-master

şeklinde kurulum yapabilirsiniz.
