### ISSUE TITLE
Invalid content was found starting with element 'cac:AllowanceCharge'. One of '{"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2":SubInvoiceLine}' is expected. LOCATOR:    LINE NUMBER:17    COLUMN NUMBER:4541 / böyle bir hata alıyorum sorunun kaynağını bulamadım yardımcı olabilir misiniz ?

### ISSUE THREAD

**Issue by gurkan-baykan** [UnlemBilisim/foribaapi#10]
$invoice_line_allowance_charge = new \Bulut\eFaturaUBL\AllowanceCharge();    
                                
         $invoice_line_allowancecharge->ChargeIndicator ="false";
         $invoice_line_allowancecharge->AllowanceChargeReason="deneme metin";
          $invoice_line_allowancecharge->MultiplierFactorNumeric= "12";
         $invoice_line_allowancecharge->SequenceNumeric=$key+1;
         $invoice_line_allowancecharge->Amount= ["val" =>  $urun['birim_fiyat'], 'attrs' => ['currencyID="TRY"']];
     $invoice_line_allowancecharge->BaseAmount = ["val" => $urun['birim_fiyat'], 'attrs' => ['currencyID="TRY"'] 
$invoice_line->AllowanceCharge = $invoice_line_allowancecharge;

**Comment by Orgenus** [comment]
UBL çıktısını alıp Foriba ile paylaşırsanız yardımcı olacaklardır.

**Comment by gurkan-baykan** [comment]
merhaba orgenus bu problemi foribaya ilettim fakat onlar biz php dili desteği veremiyoruz dediler bana yardımcı olabilir misin problemi çözmek için

**Comment by Orgenus** [comment]
Oluşturmuş olduğunuz UBL'i paylaşır mısınız ?

**Comment by gurkan-baykan** [comment]
[UBL.xml.zip](https://github.com/UnlemBilisim/foribaapi/files/2859589/UBL.xml.zip)

Sizin ubl oluşturmada kullandığınız kodun birebir aynısını yazıp hiçbir değişiklik yapmadan da denedim aynı hata yine veriyor sizde denersiniz githubda paylaşılan kodu hatayı görüceksiniz hatan veren kod bloğu $invoice_line->AllowanceCharge ile başlayan kod yapsıdır umarım yardımcı olursunuz teşekkürler

**Comment by gurkan-baykan** [comment]
Merhaba Orgenus,
Size gönderdiğim ubl yi incelediniz mi acaba  geri dönüş alamadım da

**Comment by Orgenus** [comment]
Merhabalar, UBL şematron hatası, AllowanceCharge parametresini LineExtensionAmount'dan sonraya eklersen sorun çözülür sadece yer değiştirmen gerekli.

**Comment by gurkan-baykan** [comment]
Merhaba Orgenus,
Zaten lineExtensionAmout'dan sonra koydum sizin belirttiğiniz şekilde yazdığım halde hatayı veriyor isterseniz kodumu sizinle paylaşabilirim yaklaşık 5 gündür burda takılı kaldım foriba da pek yardımcı olmadı siz bakabilir misiniz acaba diğer taraftan github da paylaşılan kodu hiç ellemeden kopyalayıp yapıştrıdığım halde bile orda da aynı hatayı aldım acaba kütüphanem demi bir problem var anlayamadım

**Comment by Orgenus** [comment]
merhabalar benim kodu inceleyip çözmemi isterseniz. obasli@unlembilisim.com adresinden özel olarak ulaşabilirsiniz. Orada gerekli detayları görüşebiliriz.

**Comment by gurkan-baykan** [comment]
tamamdır adresinize gönderiyorum

**Comment by hurkan-sert** [comment]
Merhaba Orgenus,
Diğer vergi türlerini nasıl ekliyoruz sadece kdv ekliyor fakat ben ayrı bir sütunda ürün başına diğer vergi türlerini de listelemek istiyorum örnek olarak: ÇEVRE TEMİZLİK VERGİSİ ni eklemek istiyorum bunu nasıl yapabilirim acaba yardımcı olur musunuz ?

**Comment by gurkan-baykan** [comment]
Merhaba orgenus ,
KDV dışında diğer vergi türlerini eklediğimde eklediklerim portal da gözükmüyor sadece KDV gözüküyor html table içinde ürün başına Diğer vergi türleri isimli sütun alan açılmıyor bunun sebebi nedir.UBL çıktım hepsi doğru gözküyor lütfen yardımcı olur musun ?

**Comment by Orgenus** [comment]
Foriba ile görüşün.

**Comment by hurkan-sert** [comment]
Merhaba Orgenus,
 gelen giden faturayı sorgulamada buraya ne yazılcak gb etiketi neyi ifade ediyor anlamadım.
$getUblRequest->setIdentifier("SORGULAYAN_PK"); // veya GB

**Comment by hurkan-sert** [comment]
Merahaba Orgenus ,
Rapor sorgulama nasıl yapıyor dokümanlarda mevcut değil sanırsam yardımcı olabilir misiniz ?

**Comment by hurkan-sert** [comment]
Merahaba Orgenus ,
fatura durumu sorgulatıyorum fakat gönderici etiketine ne yazılcak bilmiyorum bunu nerden alırım portal de gönderici etiketi yazıyor fakat hata alıyorum sürekli
  $getUblRequest->setIdentifier(""); // veya GB
                    $getUblRequest->setVKNTCKN("1680519679"); 
                    $getUblRequest->setDocType("INVOICE"); // veya ENVOLOPE
                    $getUblRequest->setType("INBOUND"); // veya OUTBOUND
                    $getUblRequest->setFromDate("2019-02-18");
                    $getUblRequest->setToDate("2019-02-19");
                    $getUblRequest->setFromDateSpecified(true);
                    $getUblRequest->setToDateSpecified(true);
