### ISSUE TITLE
DocumentReference'de Attachment Kullanımı

### ISSUE THREAD

**Issue by abdullahckr** [UnlemBilisim/foribaapi#12]
Merhabalar,
DocumentReference alanında base64 ile encode edilmiş resim göndermem gerekmektedir. 
AdditionalDocumentReference de 
/**
     * @var |Bulut|eFaturaUBL|Attachment
     */
public $Attachment;

bulunmakatdır, Attachment da ise 
/**
     * @var |Array ( attrs = [mimeCode="application/zip", encodingCode="Base64", characterSetCode="UTF-8", filename="91BD2213-767A-47E4-9C76-5C6F212A637F.zip"])
     */
    public $EmbeddedDocumentBinaryObject;

bunlar bulunmaktadır. Aşağıdaki örnek çıktıyı alabilmek için nasıl bir tanımlama yapmam gerekiyor. Yardımcı olabilir misiniz?

<cac:Attachment>
<cbc:EmbeddedDocumentBinaryObject mimeCode="image/png" encodingCode="Base64" filename="Barkod">base64resimkodlari</cbc:EmbeddedDocumentBinaryObject>
</cac:Attachment>

**Comment by Orgenus** [comment]
Örnek kodlarda benzer kodlar var inceleyip bulabilirsiniz.
