### ISSUE TITLE
kurulumu birtürlü yapamadım. lütfen yardımcı olurmusunuz?

### ISSUE THREAD

**Issue by ocangir** [UnlemBilisim/foribaapi#20]
Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found in C:\xampp\htdocs\fatura\src\Bulut\FITApi\FITInvoiceService.php:63 Stack trace: #0 C:\xampp\htdocs\fatura\example\Code.php(434): Bulut\FITApi\FITInvoiceService->__construct(Array, true) #1 C:\xampp\htdocs\fatura\example\pages\faturagonder.php(13): SendUBlInv('E9F63683-7D49-4...', '<?xml version="...', 'INVOICE', 'omer', 'omer') #2 C:\xampp\htdocs\fatura\example\index.php(97): include('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\fatura\src\Bulut\FITApi\FITInvoiceService.php on line 63

**Comment by Orgenus** [comment]
Konu ile alakalı foriba ile görüşebilirsiniz.
