### ISSUE TITLE
E-Arşiv Fatura Gönderme

### ISSUE THREAD

**Issue by abdullahckr** [UnlemBilisim/foribaapi#3]
Merhabalar,
EArsivFaturaGonder fonksiyonunu kullanıp deneme amaçlı bir fatura gönderdiğimde dönen sonuç aşağıdaki şekildedir. Oluşturulan xml şema/şematron kontrolünden geçmektedir. Bu konuda yardımcı olabilirseniz sevinirim.

Bulut\ArchiveService\SendInvoiceResponse Object
(
    [Detail] => 25:Schema is invalid.
    [Result] => Bulut\ArchiveService\Result Object
        (
            [Result] => FAIL
        )

    [preCheckErrorResults] => Bulut\ArchiveService\preCheckErrorResults Object
        (
            [preCheckError] => Array
                (
                    [ErrorCode] => 25
                    [ErrorDesc] => Schema is invalid. null
                    [Filename] => Fatura.xml
                )

        )

    [preCheckSuccessResults] => Bulut\ArchiveService\preCheckSuccessResults Object
        (
            [preCheckSuccess] => 
        )

)

**Comment by Orgenus** [comment]
Hatanın kaynağını Foriba ile görüşerek çözüme ulaştırabilirsiniz. Yazılımsal bir problem değildir şema hataları.

**Comment by ferhatustundag** [comment]
Benzer bir hatayı biz de aldık ve Foriba ile iletişime geçtiğimizde şöyle bir dönüş yaptılar:

```
<cbc:InvoiceTypeCode>SATIŞ</cbc:InvoiceTypeCode>
<cbc:Note>Test Not</cbc:Note>
```

Yukarıdaki iki node un "peş peşe" olması gerektiği yönünde oldu. Biz ilgili sınıfları kullanırken her ne kadar bu değerleri peş peşe set etsek de sonuçta `Bulut\eFaturaUBL\Invoice` model inde bu elemanlar peş peşe olmadığı için Foriba şema hatası vermektedir. İlgili model sınıfında 

```
    /**
     * @var |String
     */
    public $InvoiceTypeCode;
    /**
     * @var |Array
     */
    public $Note;
    /**
     * @var |String
     */
    public $DocumentCurrencyCode;
    /**
     * @var |String
     */
    public $LineCountNumeric;
```

Şeklinde bir değişiklik yapıldığında bahsi geçen şema problemi ortadan kalkıyor. 

NOT: değişiklik yaptıktan sonra E-Fatura gönderim testi de yapıldı ve sorun olmadığı gözlemlendi. Kütüphane de bu değişiklik yapılabilir mi?

Çok teşekkürler, elinize sağlık

**Comment by Orgenus** [comment]
Teşekkürler gerekli güncelleme yapıldı.
