### ISSUE TITLE
ZipArchive::addFromString() expects parameter 2 to be string, object given in /*I'm getting the error did not understand the problem*/

### ISSUE THREAD

**Issue by gurkan-baykan** [UnlemBilisim/foribaapi#8]
$xml = new \Bulut\eFaturaUBL\XMLHelper($invoice);
                                
         $rand = rand(1000,9999);
         $destination = 'temp/'.$rand.'.zip';
                                
           $zip = new ZipArchive;

            if($zip->open($destination,ZIPARCHIVE::CREATE) !== true) {
               return false;
                  }
                           
             $zip->addFromString($uuid.'.xml',$xml); /*faulty row*/
                                
             $zip->close();

**Comment by Orgenus** [comment]
$xml değişkeni boş geliyor lütfen kontrol edin.

**Comment by hurkan-sert** [comment]
[Bulut\eFaturaUBL\XMLHelperobject] => Bulut\eFaturaUBL\Invoice Object
        (
            [UBLVersionID] => 2.1
            [CustomizationID] => TR1.2
            [ProfileID] => EARSIVFATURA
            [ID] => 1899999010020000010
            [CopyIndicator] => false
            [UUID] => 305D6BF5-F6D8-4039-9AC8-7D713980B2C4
            [IssueDate] => 07.02.2019 15:31:52
            [IssueTime] => 
            [InvoiceTypeCode] => SATIS
            [DocumentCurrencyCode] => TRY
            [LineCountNumeric] => 1
            [Note] => 
            [BillingReference] => 
            [AdditionalDocumentReference] => Array
                (
                    [0] => Bulut\eFaturaUBL\DocumentReference Object
                        (
                            [ID] => 0100
                            [IssueDate] => 07.02.2019 15:31:52
                            [DocumentTypeCode] => SATIS
                            [DocumentType] => 
                            [DocumentDescription] => 
                            [Attachment] => 
                        )

                    [1] => Bulut\eFaturaUBL\DocumentReference Object
                        (
                            [ID] => KAGIT
                            [IssueDate] => 07.02.2019 15:31:52
                            [DocumentTypeCode] => EREPSENDT
                            [DocumentType] => 
                            [DocumentDescription] => 
                            [Attachment] => 
                        )

                )

            [DespatchDocumentReference] => 
            [Signature] => Bulut\eFaturaUBL\Signature Object
                (
                    [ID] => Array
                        (
                            [val] => 60751223400
                            [attrs] => Array
                                (
                                    [0] => schemeID = "VKN_TCKN"
                                )

                        )

                    [SignatoryParty] => Bulut\eFaturaUBL\SignatoryParty Object
                        (
                            [PartyIdentification] => Bulut\eFaturaUBL\PartyIdentification Object
                                (
                                    [ID] => Array
                                        (
                                            [val] => 60751223400
                                            [attrs] => Array
                                                (
                                                    [0] => schemeID = "VKN"
                                                )

                                        )

                                )

                            [PostalAddress] => Bulut\eFaturaUBL\PostalAddress Object
                                (
                                    [ID] => 
                                    [Room] => 
                                    [StreetName] => 
                                    [BuildingName] => 
                                    [BuildingNumber] => 
                                    [CitySubdivisionName] => Akyazı
                                    [CityName] => Sakarya
                                    [PostalZone] => 54400
                                    [Region] => 
                                    [Country] => Bulut\eFaturaUBL\Country Object
                                        (
                                            [Name] => TÜRKİYE
                                        )

                                )

                        )

                    [DigitalSignatureAttachment] => Bulut\eFaturaUBL\DigitalSignatureAttachment Object
                        (
                            [ExternalReference] => Bulut\eFaturaUBL\ExternalReference Object
                                (
                                    [URI] => #Signature
                                )

                        )

                )

            [AccountingSupplierParty] => Bulut\eFaturaUBL\AccountingSupplierParty Object
                (
                    [Party] => Bulut\eFaturaUBL\Party Object
                        (
                            [EndpointID] => 
                            [WebsiteURI] => http://unlembilisim.com
                            [PartyIdentification] => Bulut\eFaturaUBL\PartyIdentification Object
                                (
                                    [ID] => Array
                                        (
                                            [val] => 163804554519679
                                            [attrs] => Array
                                                (
                                                    [0] => schemeID="TCKN"
                                                )

                                        )

                                )

                            [PartyName] => Bulut\eFaturaUBL\PartyName Object
                                (
                                    [Name] => dfgd
                                )

                            [PostalAddress] => Bulut\eFaturaUBL\PostalAddress Object
                                (
                                    [ID] => 
                                    [Room] => 
                                    [StreetName] => 
                                    [BuildingName] => 
                                    [BuildingNumber] => 
                                    [CitySubdivisionName] => 
                                    [CityName] => Sakarya
                                    [PostalZone] => 54400
                                    [Region] => asd
                                    [Country] => Bulut\eFaturaUBL\Country Object
                                        (
                                            [Name] => Türkiye
                                        )

                                )

                            [PartyTaxScheme] => Bulut\eFaturaUBL\PartyTaxScheme Object
                                (
                                    [TaxScheme] => Bulut\eFaturaUBL\TaxScheme Object
                                        (
                                            [Name] => ÖTV 4.Liste
                                            [TaxTypeCode] => 
                                        )

                                )

                            [Contact] => Bulut\eFaturaUBL\Contact Object
                                (
                                    [Telephone] => 05336126974
                                    [Telefax] => 
                                    [ElectronicMail] => 
                                )

                            [PhysicalLocation] => 
                            [PartyLegalEntity] => 
                            [AgentParty] => 
                            [Person] => Bulut\eFaturaUBL\Person Object
                                (
                                    [FirstName] => asd
                                    [FamilyName] => gfd
                                    [Title] => 
                                    [MiddleName] => 
                                    [NationalityID] => 
                                    [FinancialAccount] => 
                                    [IdentityDocumentReference] => 
                                )

                        )

                )

            [AccountingCustomerParty] => Bulut\eFaturaUBL\AccountingCustomerParty Object
                (
                    [Party] => Bulut\eFaturaUBL\Party Object
                        (
                            [EndpointID] => 
                            [WebsiteURI] => http://unlembilisim.com
                            [PartyIdentification] => Bulut\eFaturaUBL\PartyIdentification Object
                                (
                                    [ID] => Array
                                        (
                                            [val] => 7657567567
                                            [attrs] => Array
                                                (
                                                    [0] => schemeID="TCKN"
                                                )

                                        )

                                )

                            [PartyName] => Bulut\eFaturaUBL\PartyName Object
                                (
                                    [Name] => GIB
                                )

                            [PostalAddress] => Bulut\eFaturaUBL\PostalAddress Object
                                (
                                    [ID] => 
                                    [Room] => 01
                                    [StreetName] => 12
                                    [BuildingName] => bina adi
                                    [BuildingNumber] => 32
                                    [CitySubdivisionName] => inönü
                                    [CityName] => sakarya
                                    [PostalZone] => 54400
                                    [Region] => Marmara
                                    [Country] => Bulut\eFaturaUBL\Country Object
                                        (
                                            [Name] => Türkiye
                                        )

                                )

                            [PartyTaxScheme] => Bulut\eFaturaUBL\PartyTaxScheme Object
                                (
                                    [TaxScheme] => Bulut\eFaturaUBL\TaxScheme Object
                                        (
                                            [Name] => müsteri vergi
                                            [TaxTypeCode] => 
                                        )

                                )

                            [Contact] => Bulut\eFaturaUBL\Contact Object
                                (
                                    [Telephone] => 345345345345
                                    [Telefax] => 
                                    [ElectronicMail] => 
                                )

                            [PhysicalLocation] => 
                            [PartyLegalEntity] => 
                            [AgentParty] => 
                            [Person] => Bulut\eFaturaUBL\Person Object
                                (
                                    [FirstName] => Ali
                                    [FamilyName] => KÖSEBEY
                                    [Title] => 
                                    [MiddleName] => 
                                    [NationalityID] => 
                                    [FinancialAccount] => 
                                    [IdentityDocumentReference] => 
                                )

                        )

                )

            [TaxTotal] => Bulut\eFaturaUBL\TaxTotal Object
                (
                    [TaxAmount] => Array
                        (
                            [val] => 200
                            [attrs] => Array
                                (
                                    [0] => currencyID="TRY"
                                )

                        )

                    [TaxSubtotal] => Bulut\eFaturaUBL\TaxSubtotal Object
                        (
                            [TaxableAmount] => Array
                                (
                                    [val] => 0.99
                                    [attrs] => Array
                                        (
                                            [0] => currencyID="TRY"
                                        )

                                )

                            [TaxAmount] => Array
                                (
                                    [val] => 0.01
                                    [attrs] => Array
                                        (
                                            [0] => currencyID="TRY"
                                        )

                                )

                            [CalculationSequenceNumeric] => 
                            [Percent] => 
                            [TaxCategory] => Bulut\eFaturaUBL\TaxCategory Object
                                (
                                    [TaxScheme] => Bulut\eFaturaUBL\TaxScheme Object
                                        (
                                            [Name] => KDV
                                            [TaxTypeCode] => 0015
                                        )

                                    [TaxExemptionReasonCode] => 
                                    [TaxExemptionReason] => 
                                )

                        )

                )

            [LegalMonetaryTotal] => Bulut\eFaturaUBL\LegalMonetaryTotal Object
                (
                    [LineExtensionAmount] => Array
                        (
                            [val] => 1
                            [attrs] => Array
                                (
                                    [0] => currencyID="TRY"
                                )

                        )

                    [TaxExclusiveAmount] => Array
                        (
                            [val] => 0.99
                            [attrs] => Array
                                (
                                    [0] => currencyID="TRY"
                                )

                        )

                    [TaxInclusiveAmount] => Array
                        (
                            [val] => 1
                            [attrs] => Array
                                (
                                    [0] => currencyID="TRY"
                                )

                        )

                    [AllowanceTotalAmount] => 
                    [PayableAmount] => Array
                        (
                            [val] => 1
                            [attrs] => Array
                                (
                                    [0] => currencyID="TRY"
                                )

                        )

                )

            [BuyerCustomerParty] => 
            [PaymentMeans] => 
            [AllowanceCharge] => 
            [Delivery] => 
            [PaymentTerms] => 
            [OriginatorDocumentReference] => 
            [PaymentAlternativeExchangeRate] => 
            [InvoicePeriod] => 
            [TaxRepresentativeParty] => 
            [InvoiceLine] => Array
                (
                    [0] => Bulut\eFaturaUBL\InvoiceLine Object
                        (
                            [ID] => 1
                            [InvoicedQuantity] => Array
                                (
                                    [val] => 1
                                    [attrs] => Array
                                        (
                                            [0] => unitCode="CMT"
                                        )

                                )

                            [LineExtensionAmount] => Array
                                (
                                    [val] => 0.99
                                    [attrs] => Array
                                        (
                                            [0] => currencyID="TRY"
                                        )

                                )

                            [Item] => Bulut\eFaturaUBL\Item Object
                                (
                                    [Name] => Ürün - 1
                                    [SellersItemIdentification] => 
                                )

                            [Price] => Bulut\eFaturaUBL\Price Object
                                (
                                    [PriceAmount] => Array
                                        (
                                            [val] => 197.40
                                            [attrs] => Array
                                                (
                                                    [0] => currencyID="TRY"
                                                )

                                        )

                                )

                            [AllowanceCharge] => 
                            [TaxTotal] => 
                            [Note] => 
                        )

                )

        )

    [Bulut\eFaturaUBL\XMLHelpernamespaces] => Array
        (
            [xmlns] => urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2
            [xmlns:cac] => urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2
            [xmlns:cbc] => urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2
            [xmlns:ds] => http://www.w3.org/2000/09/xmldsig#
            [xmlns:ext] => urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2
            [xmlns:ns8] => urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2
            [xmlns:xades] => http://uri.etsi.org/01903/v1.3.2#
            [xmlns:xsi] => http://www.w3.org/2001/XMLSchema-instance
            [xsi:schemaLocation] => urn:oasis:names:specification:ubl:schema:xsd:Invoice-2 UBL-Invoice-2.1.xsd
        )

)
xml min log çıktısı

**Comment by Orgenus** [comment]
Buraya objeyi değil UBL xml vermelisiniz.

**Comment by gurkan-baykan** [comment]
nasıl veriliyor biraz yardımcı olabilir misiniz

**Comment by Orgenus** [comment]
konu hakkında Foribadan destek alabilirsiniz.
