### ISSUE TITLE
yeni şube nasıl tanımlanıyor

### ISSUE THREAD

**Issue by gurkan-baykan** [UnlemBilisim/foribaapi#9]
api üzerinden tanımlana biliyor mu yada panelden mi tanımlanıyor.Sürekli default seçeneği var

**Comment by Orgenus** [comment]
Tanımlamalar Foriba tarafından yapılmaktadır. Lütfen destek ile iletişime geçiniz.

**Comment by gurkan-baykan** [comment]
teşekkür ederim
